# Data Cleaning

Merge DFs, subset cols, create new cols

## Set Up

In [1]:
import sys
import os

sys.path.append(os.path.abspath("../"))
from src.config import BASE_PATH
from src.data_utils import import_raw_data_dict, get_feature_lists
from src.clean_filter import merge_dfs
import pandas as pd
import numpy as np
from shutil import rmtree
import warnings

### Merge DFs

In [2]:
data_path = BASE_PATH / "data" / "raw" / "cpt_filtered"
data_dict = import_raw_data_dict(data_path)
combined_df_no_codes, combined_df_w_codes = merge_dfs(data_dict, include_cpt=True)

Working on file: NSQIP_14_cpt...
Working on file: NSQIP_11_cpt...
Working on file: NSQIP_18_cpt...
Working on file: NSQIP_16_cpt...
Working on file: NSQIP_09_cpt...
Working on file: NSQIP_21_cpt...
Working on file: NSQIP_24_cpt...
Working on file: NSQIP_23_cpt...
Working on file: NSQIP_13_cpt...
Working on file: NSQIP_20_cpt...
Working on file: NSQIP_19_cpt...
Working on file: NSQIP_17_cpt...
Working on file: NSQIP_22_cpt...
Working on file: NSQIP_08_cpt...
Working on file: NSQIP_10_cpt...
Working on file: NSQIP_12_cpt...
Working on file: NSQIP_15_cpt...
1/17
2/17
3/17
4/17
5/17
6/17
7/17
8/17
9/17
10/17
11/17
12/17
13/17
14/17
15/17
16/17
17/17
Combined Shape No Codes: (8297, 80)
Combined Shape With Codes: (8297, 107)

## Clean Resulting categorical instances

In [3]:
replace_dict = {
    "SEX": {"non-bi": "non-binary"},
    "RACE_NEW": {
        "Unknown/Not Reported": "otherUnknown",
        "Unknown": "otherUnknown",
        "Some Other Race": "otherUnknown",
        "Native Hawaiian or Other Pacific Islander": "otherUnknown",
        "American Indian or Alaska": "otherUnknown",
        "Native Hawaiian or Pacifi": "otherUnknown",
        "American Indian or Alaska Native": "otherUnknown",
        "White,Black or African American": "otherUnknown",
        "Native Hawaiian or Other Pacific Islander,Asian": "otherUnknown",
        "Asian,Some Other Race": "otherUnknown",
        "Native Hawaiian or Pacific Islander": "otherUnknown",
        "American Indian or Alaskan Native": "otherUnknown",
        "White,Asian": "otherUnknown",
        "White,Native Hawaiian or Other Pacific Islander": "otherUnknown",
        "Hispanic or Latino": "otherUnknown",
        "Middle Eastern or North African": "otherUnknown",
        "NULL": "otherUnknown",
        "nan": "otherUnknown",
    },
    "ETHNICITY_HISPANIC": {
        "N": "noUnknown",
        "No": "noUnknown",
        "U": "noUnknown",
        "Unknown": "noUnknown",
        "Unk": "noUnknown",
        "Y": "Yes",
        "NULL": "noUnknown",
        "nan": "noUnknown",
    },
    "INOUT": {"Inpatient": "Yes", "Outpatient": "No"},
    "ANESTHES": {
        "None": "otherUnknown",
        "Other": "otherUnknown",
        "Monitored Anesthesia Care": "otherUnknown",
        "MAC/IV Sedation": "otherUnknown",
        "Unknown": "otherUnknown",
        "Spinal": "otherUnknown",
        "Local": "otherUnknown",
    },
    "SURGSPEC": {
        "Urology": "otherUnkown",
        "Vascular": "otherUnkown",
        "Cardiac Surgery": "otherUnkown",
        "Neurosurgery": "otherUnkown",
        "Orthopedics": "otherUnkown",
    },
    "DISCHDEST": {
        "Home": "HomePermRes",
        "Home/Permanent Residence": "HomePermRes",
        "Unknown": "otherUnknown",
        "Facility Which was Home": "HomePermRes",
        "Separate Acute Care": "Acute Care",
        "Acute Care Hospital": "Acute Care",
        "Unskilled Facility Not Home": "otherUnknown",
        "Hospice": "otherUnknown",
        "Other Facility": "otherUnknown",
        "Against Medical Advice (AMA)": "otherUnknown",
        "None": "otherUnknown",
        "NULL": "otherUnknown",
        "nan": "otherUnknown",
    },
    "URGENCY": {
        "Yes": "Urgent_Emergent",
        "No": "Elective",
        "Urgent": "Urgent_Emergent",
        "Emergent": "Urgent_Emergent",
        "Unk": "Unknown",
    },
    "DIABETES": {
        "NO": "No",
        "NON-INSULIN": "Yes",
        "INSULIN": "Yes",
        "ORAL": "Yes",
    },
    "DYSPNEA": {
        "Unknown": "otherUnknown",
        "MODERATE EXERTION": "Yes",
        "AT REST": "Yes",
        "None": "No",
    },
    "FNSTATUS2": {
        "Unknown": "otherUnknown",
        "Partially Dependent": "Dependent",
        "Partially D": "Dependent",
        "Totally Dependent": "Dependent",
        "Totally Dep": "Dependent",
    },
    "DIALYSIS": {"Ye": "Yes"},
    "WNDINF": {  # pre-op
        0: "No",
        1: "Yes",
        "None": "No",
    },
    "WTLOSS": {"Unknown": "otherUnknown", "None": "No"},
    "PRSEPIS": {"SIRS": "Yes", "Sepsis": "Yes", "None": "No", "nan": "No"},
    "SUPINFEC": {"No Complication": "No", "Superficial Incisional SSI": "Yes"},
    "ORGSPCSSI": {"No Complication": "No", "Organ/Space SSI": "Yes"},
    "DEHIS": {
        "No Complication": "No",
        "Wound Disruption": "Yes",
        "0": "No",
        "1": "Yes",
    },
    "OUPNEUMO": {"No Complication": "No", "Pneumonia": "Yes"},
    "REINTUB": {
        "No Complication": "No",
        "Unplanned Intub": "Yes",
        "Unplanned Intubation": "Yes",
    },
    "PULEMBOL": {"No Complication": "No", "Pulmonary Embolism": "Yes"},
    "FAILWEAN": {"No Complication": "No", "On Ventilator greater than 48 Hours": "Yes"},
    "RENAINSF": {
        "No Complication": "No",
        "Postop  Renal Insufficiency": "Yes",
        "Progressive Renal Insufficiency": "Yes",
        "Progressive Ren": "Yes",
        "None": "No",
        "Postop† Renal†Insufficiency": "Yes",
    },
    "RENAFAIL": {  # pre-op
        "None": "No",
    },
    "OPRENAFL": {
        "No Complication": "No",
        "Acute Renal Failure": "Yes",
        "Postop Dialysis": "Yes",
    },
    "URNINFEC": {"No Complication": "No", "Urinary Tract Infection": "Yes"},
    "CNSCVA": {"No Complication": "No", "Stroke/CVA": "Yes"},
    "CDARREST": {
        "No Complication": "No",
        "Cardiac Arrest Requiring CPR": "Yes",
        "Cardiac Arrest": "Yes",
    },
    "CDMI": {
        "No Complication": "No",
        "Myocardial Infarction": "Yes",
        "Myocardial Infa": "Yes",
    },
    "OTHBLEED": {
        "No Complication": "No",
        "Transfusions/Intraop/Postop": "Yes",
        "Blood Transfusion": "Yes",
    },
    "OTHDVT": {
        "No Complication": "No",
        "DVT Requiring Therapy": "Yes",
        "Venous Thrombosis Requiring Therapy": "Yes",
        "DVT Requiring Therap": "Yes",
    },
    "OTHSYSEP": {"No Complication": "No", "Sepsis": "Yes"},
    "OTHSESHOCK": {"No Complication": "No", "Septic Shock": "Yes"},
    "RETURNOR": {"NUL": "No"},
    "AGE": {"90+": "90", " ": "-99"},
    "ASACLAS": {
        "5-Moribund": "4/5-Life Threat/Moribund",
        "4-Life Threat": "4/5-Life Threat/Moribund",
        "None assigned": "unknown",
    },
    "YRDEATH": {"-99": "No", "-99.0": "No"},
    "UNPLREOP": {"nan": "No"},
    "READ": {"None": "No", "nan": "No"},
    "UNPLREAD": {"None": "No", "nan": "No"},
    "WNDINFD": {  # post-op
        "No Complication": "No",
        "Deep Incisional SSI": "Yes",
    },
}

# dif cleaning to fit NSQIP calc input
replace_dict_for_nsqip = {
    "AGE": {"90+": "90", " ": "-99"},
    "SEX": {"non-bi": "non-binary"},
    "FNSTATUS2": {
        "Unknown": "otherUnknown (use default independent)",
        "Partially Dependent": "Partially Dependent",
        "Partially D": "Partially Dependent",
        "Totally Dependent": "Totally Dependent",
        "Totally Dep": "Totally Dependent",
    },
    "URGENCY": {
        "Elective": "No",
        "Urgent": "Yes",
    },
    "ASACLAS": {
        "None assigned": "unknown",
    },
    # steroid doesnt need
    # ASCITES doesnt need
    "PRSEPIS": {"None": "No", "nan": "No"},
    # VENTILAT doesnt need
    # DISCANCR doesnt need
    "DIABETES": {
        "NO": "No",
        "NON-INSULIN": "non-insulin",
        "INSULIN": "insulin",
        "ORAL": "oral",
    },
    # HYPERMED doesnt need
    # HXCHF doesnt need
    # SMOKE doesnt need
    # HXCOPD doesnt need
    "DIALYSIS": {"Ye": "Yes"},
    "RENAFAIL": {  # pre-op
        "None": "No",
    },
}


df_combined = combined_df_no_codes.copy()
### Make all column lists upper case
df_combined.columns = df_combined.columns.str.upper()
# Remove leading/trailing 0s
string_cols = df_combined.select_dtypes(include=["object"]).columns
for col in string_cols:
    df_combined[col] = df_combined[col].astype(str).str.strip()
## Normalize instance names
with warnings.catch_warnings():
    warnings.filterwarnings(
        "ignore", category=FutureWarning, message=".*Downcasting behavior.*"
    )
    df_replaced = df_combined.replace(replace_dict).infer_objects(copy=False).copy()
    # Make nsqip df used for manual entry
    df_replaced_nsqip = (
        df_combined.replace(replace_dict_for_nsqip).infer_objects(copy=False).copy()
    )
## Deal with mortality
df_replaced["MORTALITY"] = np.where(df_replaced["YRDEATH"] == "No", "No", "Yes")
df_replaced = df_replaced.drop(["YRDEATH"], axis=1)
df_replaced["MORTALITY"] = np.where(
    (df_replaced["MORTALITY"] == "Yes") | (df_replaced["DISCHDEST"] == "Expired"),
    "Yes",
    df_replaced["MORTALITY"],
)
## Remove sparse entries
df_replaced = df_replaced[df_replaced["SEX"] != "non-binary"]
df_replaced = df_replaced[df_replaced["ASACLAS"] != "unknown"]
## Make operation year an INT
df_replaced["OPERYR"] = df_replaced["OPERYR"].astype(float).astype(int)
# do same for nsqip df
df_replaced_nsqip["OPERYR"] = df_replaced_nsqip["OPERYR"].astype(float).astype(int)

In [4]:
pd.crosstab(index=df_replaced['OTHSYSEP'], columns=df_replaced['OTHSESHOCK'])

OTHSESHOCK    No  Yes
OTHSYSEP
No          8161   33
Yes           80    0

Change "No"s to NA if not recorded for a given year
- NOTE: Not applicable to NSQIP bc no vars of interest missing in 2024

In [5]:
df_unknowns = df_replaced.copy()
# READ --> not recorded 08-10
df_unknowns.loc[
    (df_unknowns["READ"] == "No") & df_unknowns["OPERYR"].between(2008, 2010),
    "READ",
] = "Unknown(08-10)"
# UNPLREAD --> 08-11
df_unknowns.loc[
    (df_unknowns["UNPLREAD"] == "No") & df_unknowns["OPERYR"].between(2008, 2011),
    "UNPLREAD",
] = "Unknown(08-11)"
# RENAINSF --> 21
df_unknowns.loc[
    (df_unknowns["RENAINSF"] == "No") & (df_unknowns["OPERYR"] == 2021),
    "RENAINSF",
] = "Unknown(21)"
# RENAFAIL --> 21
df_unknowns.loc[
    (df_unknowns["RENAFAIL"] == "No") & (df_unknowns["OPERYR"] == 2021),
    "RENAFAIL",
] = "Unknown(21)"
# WTLOSS --> 21-24
df_unknowns.loc[
    (df_unknowns["WTLOSS"] == "No") & df_unknowns["OPERYR"].between(2021, 2024),
    "WTLOSS",
] = "Unknown(21-24)"
# WNDINF --> 21-24
df_unknowns.loc[
    (df_unknowns["WNDINF"] == "No") & df_unknowns["OPERYR"].between(2021, 2024),
    "WNDINF",
] = "Unknown(21-24)"
# DYSPNEA --> 21-24
df_unknowns.loc[
    (df_unknowns["DYSPNEA"] == "No") & df_unknowns["OPERYR"].between(2021, 2024),
    "DYSPNEA",
] = "Unknown(21-24)"

In [6]:
numerical_cols = get_feature_lists(df_unknowns)["numerical_cols"]
# non-numerical cols
other_cols = [col for col in df_unknowns.columns if col not in numerical_cols]
assert df_unknowns[other_cols].isna().sum().sum() == 0

other_cols_nsqip = [
    col for col in df_replaced_nsqip.columns if col not in numerical_cols
]
assert df_replaced_nsqip[other_cols_nsqip].isna().sum().sum() == 0

## Clean Numerical Features

Explore NA

In [7]:
## ALL NA values are listed as -99/999, not NA/missing
numerical_cols = get_feature_lists(df_unknowns)["numerical_cols"]
df_unknowns[numerical_cols] = df_unknowns[numerical_cols].astype(float)

df_unknowns[numerical_cols] = df_unknowns[numerical_cols].replace(-99, np.nan)
df_unknowns[numerical_cols] = df_unknowns[numerical_cols].replace(999, np.nan)
print("Proportion (%) of NA vals in feature:")
print(round((df_unknowns[numerical_cols].isna().mean() * 100), 2))

# make nsqip num cols numeric as well
df_replaced_nsqip[numerical_cols] = df_replaced_nsqip[numerical_cols].astype(float)

Proportion (%) of NA vals in feature:
CASEID      0.00
CPT         0.00
AGE         0.08
OPERYR      0.00
HEIGHT      0.71
WEIGHT      0.31
PRALBUM    57.26
PRWBC      18.37
PRHCT      16.88
PRPLATE    18.02
OPTIME      0.02
TOTHLOS     0.75
dtype: float64

Remove outliers

In [8]:
display(df_unknowns[numerical_cols].describe())
## Remove
print(f"Total removed due to 0 OPTIME: {(df_unknowns['OPTIME'] == 0).sum()}")
df_unknowns = df_unknowns[df_unknowns["OPTIME"] != 0]

,CASEID,CPT,AGE,OPERYR,HEIGHT,WEIGHT,PRALBUM,PRWBC,PRHCT,PRPLATE,OPTIME,TOTHLOS
count,8.274000e+03,8274.000000,8267.000000,8274.000000,8215.000000,8248.000000,3536.000000,6754.000000,6877.000000,6783.000000,8272.000000,8212.000000
mean,8.377315e+06,37408.172951,62.101488,2017.911651,66.320876,174.714961,4.114375,7.427378,40.571229,247.804066,272.818424,5.377983
std,4.409939e+06,8618.185202,13.250969,4.076099,4.129098,46.429732,0.480202,2.673620,4.806103,79.058849,224.869844,6.558513
min,3.644630e+05,14301.000000,19.000000,2008.000000,48.000000,57.000000,1.300000,0.200000,14.200000,1.380000,0.000000,0.000000
25%,4.183270e+06,38724.000000,54.000000,2015.000000,63.000000,141.000000,3.900000,5.720000,37.900000,197.000000,78.000000,1.000000
50%,8.803334e+06,41120.000000,63.000000,2018.000000,66.000000,170.000000,4.200000,7.000000,41.000000,238.000000,214.000000,3.000000
75%,1.217728e+07,41130.000000,71.000000,2021.000000,69.000000,200.000000,4.400000,8.600000,43.900000,289.000000,432.000000,8.000000
max,1.561380e+07,64910.000000,90.000000,2024.000000,85.000000,445.000000,7.000000,42.400000,58.000000,867.000000,1430.000000,92.000000

Total removed due to 0 OPTIME: 8

In [9]:
ids_to_include = df_unknowns["CASEID"]
df_replaced_nsqip = df_replaced_nsqip[df_replaced_nsqip["CASEID"].isin(ids_to_include)]
assert len(df_replaced_nsqip) == len(df_unknowns)

## Create Target Variables

In [10]:
### Reset indices
df_clean = df_unknowns.reset_index(drop=True)

Ensure CaseID is unique identifier

In [ ]:
### =============> Bleed
y_bleed = df_clean["OTHBLEED"].map({"No": 0, "Yes": 1}).astype(int)
df_clean["outcome_bleed"] = y_bleed
### =============> Pneumonia
y_pneumo = df_clean["OUPNEUMO"].map({"No": 0, "Yes": 1}).astype(int)
df_clean["outcome_pneumo"] = y_pneumo
### =============> Dehisence 
# y_dehis = df_clean["DEHIS"].map({"No": 0, "Yes": 1}).astype(int)
# df_clean["outcome_dehis"] = y_dehis
### =============> Unplanned Reintubation
# y_reintub = df_clean["REINTUB"].map({"No": 0, "Yes": 1}).astype(int)
# df_clean["outcome_reintub"] = y_reintub
### =============> Ventilator > 48H
# y_vent = df_clean["FAILWEAN"].map({"No": 0, "Yes": 1}).astype(int)
# df_clean["outcome_vent"] = y_vent
### =============> UnplannedReOp--> directly comparable
y_reoper = df_clean["UNPLREOP"].map({"No": 0, "Yes": 1}).astype(int)
df_clean["outcome_reoper"] = y_reoper
### =============> Sepsis --> directly comparable to systemic sepsis
# sep_cols = [
#     "OTHSYSEP",  # part of systemic sepsis
#     "OTHSESHOCK",  # part of systemic sepsis 
# ]
# y_sepsis = (df_clean[sep_cols] == "Yes").any(axis=1).astype(int)
# df_clean["outcome_sepsis"] = y_sepsis
### =============> Surgical Site Infection --> directly comparable
ssi_cols = [ 
    "SUPINFEC",  # Superficial infection
    "WNDINFD",  # Deep infection
    "ORGSPCSSI",  # Organ space infection
]
y_ssi = (df_clean[ssi_cols] == "Yes").any(axis=1).astype(int)
df_clean["outcome_ssi"] = y_ssi
### =============> Any SERIOUS Complication
serious_comp_cols = [
    "CDARREST",  # cardiac arrest
    "CDMI",  # myocardial infarction
    "OUPNEUMO",  # pneumonia
    # NOT including progressive renal insuffisiency (missing 21)
    # NOT including acute renal failure (missing 21)
    "PULEMBOL",  # pulmenary embolism
    "OTHDVT",  # venous thrombosis
    "UNPLREOP",  # ulanned return to OR
    "WNDINFD",  # deep incisional SSI
    "ORGSPCSSI",  # organ space SSI
    "OTHSYSEP",  # part of sysrtemic sepsis
    "OTHSESHOCK",  # part of sysrtemic sepsis
    "REINTUB",  # unplanned intubation
    "URNINFEC",  # UTI
    "DEHIS",  # wound disruption (dehisence)
]
y_serious = (df_clean[serious_comp_cols] == "Yes").any(axis=1).astype(int)
df_clean["outcome_serious"] = y_serious
### =============> ANY Complication
any_comp_cols = [
    "SUPINFEC",  # Superficial SSI
    "WNDINFD",  # Deep SSI --> in serious
    "ORGSPCSSI",  # Organ SSI --> in serious
    "DEHIS",  # Wound disruption (Dehisence) --> in serious
    "OUPNEUMO",  # pneumonia --> in serious
    "REINTUB",  # unplanned intubation --> in serious
    "PULEMBOL",  # pulmenary embolism --> in serious
    "OTHDVT",  # venous thrombosis --> in serious
    "FAILWEAN",  # Ventilator > 48hrs
    # NOT including progressive renal insuffisiency (missing 21)
    # NOT including acute renal failure (missing 21)
    "URNINFEC",  # UTI --> in serious
    "CNSCVA",  # Stroke
    "CDARREST",  # cardiac arrest --> in serious
    "CDMI",  # myocardial infarction --> in serious
    "UNPLREOP",  # ulanned return to OR --> in serious
    "OTHSYSEP",  # part of sysrtemic sepsis --> in serious
    "OTHSESHOCK",  # part of sysrtemic sepsis --> in serious
]
y_any = (df_clean[any_comp_cols] == "Yes").any(axis=1).astype(int)
df_clean["outcome_any"] = y_any

## Export

Outcomes

In [12]:
## Df w/ outcomes
df_path = BASE_PATH / "data" / "processed" / "fully_cleaned_tongue_data.xlsx"
if df_path.exists():
    df_path.unlink()
    warnings.warn(f"Over-writing tabular data at {df_path}")
df_path.parent.mkdir(exist_ok=True, parents=True)
df_clean.to_excel(df_path, index=True)

## Create ds for manual NSQIP data entry

In [13]:
# dummy var
df_replaced_nsqip["OxygenSupport (All No)"] = "NO"
nsqip_input_cols = [
    "CASEID",
    "CPT",
    "AGE",
    "SEX",
    "FNSTATUS2",
    "URGENCY",
    "ASACLAS",
    "STEROID",  # NSQIP also includes anti-rejection/transplant immunosuppressants, DMARDs/DMDs, or other immunosuppressant medications
    "ASCITES",
    "PRSEPIS",  # do not have spetic shock, only SIRS and Sepsis (in this col)
    "VENTILAT",
    "DISCANCR",
    "DIABETES",  # we have non-insulin
    "HYPERMED",
    "HXCHF",
    "OxygenSupport (All No)",  # we do not have oxygen support (only 2024?)
    "SMOKE",
    "HXCOPD",
    "DIALYSIS",
    "RENAFAIL",
    "HEIGHT",
    "WEIGHT",
]
df_nsqip = df_replaced_nsqip[df_replaced_nsqip["OPERYR"] == 2024][nsqip_input_cols]
df_nsqip

,CASEID,CPT,AGE,SEX,FNSTATUS2,URGENCY,ASACLAS,STEROID,ASCITES,PRSEPIS,...,DIABETES,HYPERMED,HXCHF,OxygenSupport (All No),SMOKE,HXCOPD,DIALYSIS,RENAFAIL,HEIGHT,WEIGHT
7568,14654144.0,15758.0,74.0,male,Independent,No,3-Severe Disturb,No,No,No,...,non-insulin,Yes,No,NO,No,No,No,No,73.0,232.0
7569,14977254.0,15757.0,63.0,female,Independent,No,3-Severe Disturb,No,No,No,...,No,Yes,No,NO,No,No,No,No,58.0,175.0
7570,15083048.0,15758.0,69.0,female,Independent,No,3-Severe Disturb,No,No,No,...,non-insulin,Yes,Yes,NO,No,No,No,No,66.0,130.0
7571,15079970.0,15757.0,56.0,female,Independent,No,3-Severe Disturb,No,No,No,...,No,No,No,NO,Yes,No,No,No,64.0,78.0
7572,15216801.0,15757.0,52.0,male,Independent,No,3-Severe Disturb,No,No,No,...,No,Yes,Yes,NO,No,No,No,No,66.0,140.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8292,15387374.0,15757.0,71.0,male,Independent,No,3-Severe Disturb,No,No,No,...,No,Yes,No,NO,No,No,No,No,68.0,215.0
8293,15457408.0,15757.0,76.0,female,Totally Dependent,No,4-Life Threat,No,No,No,...,insulin,Yes,Yes,NO,No,Yes,No,No,65.0,-99.0
8294,15521398.0,15757.0,57.0,male,Independent,No,3-Severe Disturb,No,No,No,...,No,Yes,No,NO,Yes,No,No,No,67.0,178.0
8295,15523344.0,41120.0,71.0,male,otherUnknown (use default independent),No,3-Severe Disturb,No,No,No,...,insulin,Yes,No,NO,Yes,No,No,No,68.0,217.0
8296,15363479.0,41120.0,57.0,female,Independent,No,3-Severe Disturb,No,No,No,...,non-insulin,No,No,NO,No,No,No,No,61.0,264.0

In [14]:
## Add cols
# Serious Complication
df_nsqip["Serious_Comp_NoAdj"] = None
df_nsqip["Serious_Comp_ModRisk"] = None
df_nsqip["Serious_Comp_HighRisk"] = None
# Any complication
df_nsqip["Any_Comp_NoAdj"] = None
df_nsqip["Any_Comp_ModRisk"] = None
df_nsqip["Any_Comp_HighRisk"] = None
# Return to OR
df_nsqip["Return_OR_NoAdj"] = None
df_nsqip["Return_OR_ModRisk"] = None
df_nsqip["Return_OR_HighRisk"] = None

In [15]:
## Rename cols
df_nsqip = df_nsqip.rename(
    columns={
        "FNSTATUS2": "FuncStatus",
        "URGENCY": "Emergency Case",
        "STEROID": "ImmunosuppTherapy",
        "ASCITES": "Ascites (All no)",
        "PRSEPIS": "SystemicSepsis",
        "VENTILAT": "VentDep (All no)",
        "DISCANCR": "DissemCancer",
        "HYPERMED": "Hypertension",
        "HXCHF": "CongHeartFail",
        "HXCOPD": "HistOfCOPD",
        "RENAFAIL": "AcuteKidInj (All no)",
        "HEIGHT": "HEIGHT (in)",
        "WEIGHT": "WEIGHT (lbs)",
    }
)

In [16]:
df_nsqip = df_nsqip.reset_index(drop=True)
df_nsqip[["CASEID", "CPT"]] = df_nsqip[["CASEID", "CPT"]].astype(str)
df_nsqip.to_excel(BASE_PATH / "data" / "processed" / "blank_tongue_nsqip_2024.xlsx")